const SET_POPULARLIST_LOADING = 'SET_POPULARLIST_LOADING';
const SET_POPULARLIST_SUCCESS = 'SET_POPULARLIST_SUCCESS';
const SET_POPULARLIST_FAILURE = 'SET_POPULARLIST_FAILURE';

export {
    SET_POPULARLIST_LOADING,
    SET_POPULARLIST_SUCCESS,
    SET_POPULARLIST_FAILURE,
};
